apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: titilerx-ingress
  annotations:
    spec.ingressClassName: nginx
spec:
  rules:
    - host: titilerx.eks.dec.earthdaily.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: titilerx-service
                port:
                  number: 8000