apiVersion: apps/v1
kind: Deployment
metadata:
  name: titilerx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: titilerx
  template:
    metadata:
      labels:
        app: titilerx
    spec:
      containers:
        - name: titilerx
          image: public.ecr.aws/k4l9p8h0/eoepca/titilerx:0.0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: TITILER_XARRAY_CACHE_HOST
              value: titilerx-redis
          resources:
            requests:
              memory: "4Gi"
              cpu: "2"
            limits:
              memory: "8Gi"
              cpu: "4"
